[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Tambahkan proxy untuk backend jika diperlukan
# [[redirects]]
#   from = "/api/*"
#   to = "https://sinfopers.my.id/api/:splat"
#   status = 200
#   force = true
