# Generated by Django 5.1.6 on 2025-03-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset', models.BooleanField(default=False)),
                ('child', models.ManyToManyField(blank=True, related_name='child_list', to='organizational_structure.nodes')),
                ('child_offsets', models.ManyToManyField(blank=True, related_name='child_offsets_list', to='organizational_structure.nodes')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel_database.userpersonil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120)),
                ('nodes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizational_structure.nodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
