# Generated by Django 5.1.6 on 2025-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffingstatus',
            options={'verbose_name': 'Status Kepegawaian', 'verbose_name_plural': 'Status Kepegawaian'},
        ),
        migrations.AlterField(
            model_name='staffingstatus',
            name='dsp',
            field=models.IntegerField(default=0, help_text='Daftar Susunan Personel - Jumlah personel yang seharusnya mengisi posisi ini', verbose_name='DSP'),
        ),
        migrations.AlterField(
            model_name='staffingstatus',
            name='rill',
            field=models.IntegerField(default=0, help_text='Jumlah personel aktual yang saat ini mengisi posisi ini', verbose_name='Riil'),
        ),
    ]
