# Generated by Django 5.1.6 on 2025-03-18 06:10

import personnel_database.models.pangkat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120, unique=True)),
                ('tipe', models.CharField(choices=[('PNS POLRI', 'PNS_POLRI'), ('POLRI', 'POLRI')], default=personnel_database.models.pangkat.Pangkat.Tipe['POLRI'], max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubSatKer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
