# Generated by Django 5.1.6 on 2025-03-20 09:51

import django.core.validators
import django.db.models.deletion
import personnel_database.models.pangkat
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=240, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120, unique=True)),
                ('tipe', models.CharField(choices=[('PNS POLRI', 'PNS_POLRI'), ('POLRI', 'POLRI')], default=personnel_database.models.pangkat.Pangkat.Tipe['POLRI'], max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubDit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubSatKer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPersonil',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('nrp', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('jenis_kelamin', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=12)),
                ('bko', models.CharField(choices=[('Gasus masuk', 'GASUS_MASUK'), ('Gasum masuk', 'GASUM_MASUK'), ('Gasus keluar', 'GASUS_KELUAR'), ('Gasum keluar', 'GASUM_KELUAR'), ('-', 'NOT_GASUS')], max_length=12)),
                ('status', models.CharField(choices=[('Aktif', 'AKTIF'), ('Non Aktif', 'NON_AKTIF'), ('Cuti', 'CUTI'), ('Pensiun', 'PENSIUN')], max_length=20)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.jabatan')),
                ('pangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.pangkat')),
                ('subdit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subdit')),
                ('subsatker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subsatker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
