# Generated by Django 5.1.6 on 2025-05-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0002_alter_userpersonil_options_alter_userpersonil_nrp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpersonil',
            name='bko',
            field=models.CharField(choices=[('Gasus masuk', 'GASUS_MASUK'), ('Gasum masuk', 'GASUM_MASUK'), ('Gasus keluar', 'GASUS_KELUAR'), ('Gasum keluar', 'GASUM_KELUAR'), ('-', 'NOT_GASUS')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpersonil',
            name='status',
            field=models.CharField(choices=[('Aktif', 'AKTIF'), ('Non Aktif', 'NON_AKTIF'), ('Cuti', 'CUTI'), ('Pensiun', 'PENSIUN')], default='Aktif', max_length=12),
        ),
    ]
