# Generated by Django 5.1.6 on 2025-05-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0003_alter_userpersonil_user'),
        ('personnel_database', '0003_userpersonil_user_alter_userpersonil_bko_and_more'),
    ]

    operations = [
    ]
