# Generated by Django 5.1.6 on 2025-05-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0002_auto_link_personil_user'),
        ('personnel_database', '0005_alter_userpersonil_user'),
    ]

    operations = [
    ]
