# Generated by Django 5.1.6 on 2025-05-01 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('jenis_permohonan', models.CharField(choices=[('Cuti', 'Cuti'), ('Mutasi', 'Mutasi')], default='Cuti', max_length=50)),
                ('alasan', models.TextField()),
                ('file_pendukung', models.FileField(blank=True, null=True, upload_to='permohonan/')),
                ('status', models.CharField(choices=[('pending_hr', 'Menunggu Persetujuan HR'), ('pending_pimpinan', 'Menunggu Persetujuan Pimpinan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending_hr', max_length=50)),
                ('catatan_hr', models.TextField(blank=True, null=True)),
                ('catatan_pimpinan', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permohonan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permohonan',
                'verbose_name_plural': 'Permohonan',
                'ordering': ['-date_created'],
            },
        ),
    ]
