# Generated by Django 5.1.6 on 2025-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan',
            name='status',
            field=models.CharField(choices=[('pending_hr', 'Menunggu Validasi HR'), ('valid', 'Valid - Menunggu Persetujuan Pimpinan'), ('tidak_valid', 'Tidak Valid - Dikembalikan ke Personel'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending_hr', max_length=50),
        ),
    ]
