# Generated by Django 5.2 on 2025-06-04 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0003_permohonan_hr_review_date_permohonan_hr_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonan',
            name='jumlah_hari',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permohonan',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permohonan',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SaldoCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('hak_cuti', models.PositiveIntegerField(default=12)),
                ('cuti_diambil', models.PositiveIntegerField(default=0)),
                ('sisa_bawa_tahun_lalu', models.PositiveIntegerField(default=0)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_cuti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tahun'],
                'unique_together': {('personel', 'tahun')},
            },
        ),
    ]
