# Generated by Django 5.1.6 on 2025-03-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('dsp', models.IntegerField(default=0)),
                ('rill', models.IntegerField(default=0)),
                ('pangkat', models.ManyToManyField(to='personnel_database.pangkat')),
                ('subsatker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_database.subsatker')),
            ],
        ),
    ]
