# Generated by Django 5.1.6 on 2025-05-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_status', '0002_alter_staffingstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffingstatus',
            name='rill',
        ),
    ]
