# Generated by Django 5.1.6 on 2025-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('pimpinan', 'Pimpinan'), ('anggota', 'Anggota')], default='anggota', max_length=20),
        ),
    ]
