# Generated by Django 5.1.6 on 2025-05-01 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpersonil',
            options={'verbose_name': 'Personel', 'verbose_name_plural': 'Personel'},
        ),
        migrations.AlterField(
            model_name='userpersonil',
            name='nrp',
            field=models.IntegerField(error_messages={'unique': 'NRP sudah digunakan oleh personel lain.'}, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
