# Generated by Django 5.1.6 on 2025-05-23 01:50

import django.db.models.deletion
import information.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('information_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('information_title', models.CharField(max_length=50)),
                ('information_context', models.TextField()),
                ('file_pendukung', models.FileField(blank=True, help_text='Anda dapat mengunggah file PDF sebagai lampiran pendukung', null=True, upload_to='Information/', validators=[information.models.validate_file_extension])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Information',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InformationLog',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.information')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
