# Generated by Django 5.1.6 on 2025-05-18 06:01

import django.db.models.deletion
import permohonan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0002_alter_permohonan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permohonan',
            name='hr_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permohonan',
            name='hr_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_validasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permohonan',
            name='pimpinan_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permohonan',
            name='pimpinan_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pimpinan_persetujuan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='file_pendukung',
            field=models.FileField(blank=True, help_text='Wajib mengunggah file PDF sebagai lampiran pendukung', null=True, upload_to='permohonan/', validators=[permohonan.models.validate_file_extension]),
        ),
    ]
